## Credit to: https://gist.github.com/ciiqr/31af63601a4b52a05133cf2c87e022e3

name: example-client-payload-action
on:
  repository_dispatch:
    types:
      - app-backend
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "${{ secrets.GH_REPO_APP_BACKEND }}"
          token: "${{ secrets.GH_TOKEN }}"
          ref: "${{ github.event.client_payload.tag }}"

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "${{ secrets.VAULT_URL }}"
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/gitea-actions/harborCredentials password | REGISTRY_TOKEN ;
            secret/data/gitea-actions/harborCredentials username | REGISTRY_USERNAME

      - name: Step 1
        run: echo "IMAGE_TAG=$(echo ${{ github.event.client_payload.tag }} | sed -e 's|release-||')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DH_REGISTRY }}/${{ secrets.DH_REPO_APP_BACKEND }}
          tags: |
            ${{ env.IMAGE_TAG }}

      - name: Log in to ${{ secrets.DH_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DH_REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build linux/amd64 image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: ./
          file: ./compose/production/django/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          outputs: type=image,name=${{ secrets.DH_REGISTRY }}/${{ secrets.DH_REPO_APP_BACKEND }},push-by-digest=true,name-canonical=true,push=true
      -
        name: Export digest | ${{ matrix.arch }}
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest | ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      # - name: Step 4
      #   run: echo ${{ github.event.action }}
      #   if: github.event.action == 'awesomeness'
